name: Deploy
on:
  push:
    branches:
      - main
  # schedule:
  # - cron: '30 0 * * *'
jobs:
  deploy:
    name: "Deploy website"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1.0.0
      - uses: dcodeIO/setup-node-nvm@master
        with:
          node-version: current
      - name: Build
        run: |
          npm ci --no-audit
          npm run build
      - name: Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd src/.vuepress/dist
          # echo www.assemblyscript.org > CNAME
          git init -b pages
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add -A
          git commit -m 'deploy'
          git push -f https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git pages:gh-pages
